### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/neat.bourbon.io#23]
Broken link to a `grid-span` feature:

![screen shot 2016-11-15 at 10 07 27](https://cloud.githubusercontent.com/assets/903327/20310821/5fb42a7c-ab1b-11e6-8a9b-e3a873e12a55.png)

**Comment by whmii** [comment]
Ah, this should be grid-column

**Comment by whmii** [comment]
my b

**Comment by whmii** [comment]
fixed
