### ISSUE TITLE
Repo relevant vs gh-pages?

### ISSUE THREAD

**Issue by dijonkitchen** [thoughtbot/neat.bourbon.io#28]
Is this really the repo for the website or is it really being generate from the GitHub Pages site on the main Neat repo? https://github.com/thoughtbot/neat/tree/gh-pages

Looking at http://neat.bourbon.io/, it seems like the latter.

**Comment by whmii** [comment]
hi @dijonkitchen, this is the 'new' site for the upcoming 2.0 release. We are waiting to switch the site over until the new release goes live (likely this friday). After that the `gh-pages` will either be deprecated or removed. You can preview the new page at http://neat.netlify.com

**Comment by dijonkitchen** [comment]
Gotcha!
